
platform :ios, '8.0'
pod 'MZTimerLabel'
pod 'youtube-ios-player-helper', :git=>'https://github.com/youtube/youtube-ios-player-helper', :commit=>'head'
pod 'ChameleonFramework/Swift'
pod 'Alamofire', '~> 3.0'
use_frameworks!
